### ISSUE TITLE
我使用的mac但是不知道怎么电脑上运行，师兄可以教教我吗

### ISSUE THREAD

**Issue by sukai-cheng** [sky5454/30daysMakeOS-Origin-ISOfiles#2]

**Comment by sky5454** [comment]
再不行直接虚拟机运行，毕竟汇编后的二进制是可以直接从 BIOS 启动的

**Comment by sukai-cheng** [comment]
虚拟机安装什么操作系统？

**Comment by sky5454** [comment]
> 虚拟机安装什么操作系统？

编译环境： `Windows`  
运行环境：基于  书中说明的架构的  `裸机 BIOS 启动` / `QEMU 等模拟 BIOS 环境`

**Comment by sukai-cheng** [comment]
师兄，你被我搞烦死了吧哈哈😄，我知道该怎么做啦，我基于虚拟机，把引导程序加载到软盘，让计算机从软盘启动。本来还想折腾一下qemu的，后来想想算了，最重要的还是学习操作系统，那么再见啦师兄，我学习去了
