### ISSUE TITLE
关于您在博客园的博客 存在一些疑问想讨论下

### ISSUE THREAD

**Issue by xwwwb** [sky5454/30daysMakeOS-Origin-ISOfiles#4]
https://www.cnblogs.com/yucloud/p/10943215.html 这一篇里
>ORG 0x7c00  就是让主板从内存0x7c00处开始加载我们写的helloos.img。

> 可以猜得出，day1版本是用了相对地址，在源码中 把helloos.img的开头用0x0000表示，所以实际在哪个内存地址被加载 应该是由汇编编译器或主板BIOS决定的，

> 而day2用了绝对地址，指定helloos.img要在内存0x7c00处加载。

这三句话中的第一句话：ORG应该是告诉编译器 该程序会被加载到0x7c00 而不是 告诉主板从0x7c00处开始加载
参考资料是：https://zhuanlan.zhihu.com/p/100757410?from_voters_page=true 
ORG 原理
ORG是不会产生编译结果的

` 0xeb, 0x4e, 0x90` 这段指令是 jmp short 基于当前ip的地址短跳转0x4e 
及day02中的 JMP entry 等于 day01中的 0xeb, 0x4e, 0x90

下面的RESB补0x00中，因为day02指定了ORG 所以要用0x7dfe - $ 此时的
day01由于没有写ORG 直接就是0x1fe - $ 了 

day02的$可能等于day01的$ + 0x7c00 
所以最后补的0x00数量是一致的

**Comment by xwwwb** [comment]
0x4e换算成十进制是78 查一下会发现 0x4e到entry差了78字节

**Comment by sky5454** [comment]
你好，当年的文笔手法的确比较稚嫩。

以下是NASM官方手册的说明：
[NASM - The Netwide Assembler/8.1.1-ORG](https://www.nasm.us/doc/nasmdoc8.html#section-8.1.1)

![image](https://github.com/sky5454/30daysMakeOS-Origin-ISOfiles/assets/12370628/df8bfbcb-c9cd-4833-8ae5-40c0f4d249cd)

这是博客的更正：
![image](https://github.com/sky5454/30daysMakeOS-Origin-ISOfiles/assets/12370628/eea8cfe6-ca83-47fa-8732-21b43c8030b0)

**Comment by xwwwb** [comment]
嗯，然后day01中的汇编代码 写的0x74 0x7c 也就是day02的 `MOV		SI,msg` msg标签的真实地址 
<img width="678" alt="image" src="https://github.com/sky5454/30daysMakeOS-Origin-ISOfiles/assets/16056822/70faa81f-5de2-46a8-84e6-c4989da80ad5">

您的文章对我帮助很大 感谢
